<!-- SPDX-FileCopyrightText: 2026 Philip <philip@decentsoftwa.re>
     SPDX-License-Identifier: AGPL-3.0-or-later -->
<script setup lang="ts">
/**
 * A QR code, rendered as an image rather than injected as markup.
 *
 * The SVG comes from the server and is generated by segno from a
 * server-issued token, so v-html was not exploitable in practice. But an
 * <img> cannot execute script no matter what the SVG contains, which makes
 * this a structural guarantee instead of an argument about provenance — and
 * this markup is displayed on a screen pointed at a room full of people.
 */
import { computed } from 'vue'

const props = defineProps<{ svg: string; label: string }>()

const source = computed(() => {
	// btoa cannot handle non-Latin-1; encodeURIComponent always can
	return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(props.svg)}`
})
</script>

<template>
	<img class="cz-qr-image" :src="source" :alt="label" />
</template>
